@startuml ExprEngine

class ExprEngine
{
    +ExprEvalResult Evaluate(string expression_string, ExprContext* context = nullptr);
    +void SetCurrentContext()
    +ExprContext* current_context() const;
    -unordered_map<string, ExprContext> context_map_;
}

class ExprContext
{
    +void AddEquation(Equation equation);
    +void AddEquation(const string& name, Expression expression);
    +void AddEquation(const string& name, string expression_string);
    +Equation GetEquation(string name);
    +vector<string> GetEquationNames();
    +bool UpdateAllEquations();
    +bool UpdateEquation(string name);
    -unordered_map<string, Equation> equations_;
}

enum ExprResultType
{
    STRING,
    INTEGER,
    FLOAT,
    BOOLEAN,
    LIST,
    DICT,
    FUNCTION,
    TUPLE,
    SET,
    UNKNOWN
}

class ExprResult
{
    +string ToString() = 0;
    +int ToInt() = 0;
    +float ToFloat() = 0;
    +bool ToBool() = 0;
    +list ToList() = 0;
    +vector ToVector() = 0;
    +unordered_map ToDict() = 0;
    +functional ToFunction() = 0;
    +unordered_set ToSet() = 0;
    -ExprResultType type_;
}

enum ExprErrorType
{
    SYNTAX_ERROR,
    TYPE_ERROR,
    RUNTIME_ERROR,
    EVALUATION_ERROR
}

struct ExprEvalResult
{
    - ExprResult result_;
    - bool is_success_;
    - ExprErrorType error_type_;
    - string error_message_;
}

class Expression
{
    +Expression(string expression_string, ExprContext* context);
    +string expression_string() const;
    -ExprContext* context() const;
    -string expression_string_;
    -ExprContext* context_;
    -ExprEvalResult eval_result_;
}

class Variable
{
    +string name() const;
    +ExprResult result() const;
    -string name;
    -ExprResult result_;
}

class Equation
{
    +string name() const;
    +Expression expression() const;
    +vector<string> dependencies() const;
    +vector<string> dependent() const;
    +bool is_dirty() const;
    +void set_dirty(bool dirty);
    -string name_;
    -Expression expression_;
    -vector<string> dependencies_;
    -vector<string> dependent_;
    -bool is_dirty_;
}

class PyExprEngine;

class PyExprContext;

class PyExprResult;

@enduml